# Generated by Django 5.1.4 on 2025-01-23 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_trainer', '0002_alter_member_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
